name: "vou-be"
services:
  
  #############################
  ########## EXTENSION ########
  #############################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    restart: always
    depends_on:
      - elasticsearch
    
  redis:
    image: redis:7
    restart: always
    
  zipkin:
    image: openzipkin/zipkin
    restart: always
  
  #############################
  ######### DATABASE ##########
  #############################
  voudb:
    image: postgres
    
  #############################
  ######### SERVICES ##########
  #############################  
  
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
  
  authserver:
    image: ${DOCKER_REGISTRY-}authserver
    build:
      context: .
      dockerfile: src/AuthServer/Dockerfile
      
  eventservice:
    image: ${DOCKER_REGISTRY-}eventservice
    build:
      context: .
      dockerfile: src/EventService/Dockerfile
      
  gameservice:
    image: ${DOCKER_REGISTRY-}gameservice
    build:
      context: .
      dockerfile: src/GameService/Dockerfile
      
  paymentservice:
    image: ${DOCKER_REGISTRY-}paymentservice
    build:
      context: .
      dockerfile: src/PaymentService/Dockerfile
      
  #############################
  ######## BACKGROUND #########
  #############################
  
volumes:
  db-data:
  redis-data:
  elasticsearch-data:
  kibana-data:
  zipkin-data:
