apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
      
      
#apiVersion: dapr.io/v1alpha1
#kind: Component
#metadata:
#  name: pubsub
#spec:
#  type: pubsub.kafka
#  version: v1
#  metadata:
#    - name: brokers
#      value: localhost:9092 # Change to your Kafka broker address
