services:
  
  #############################
  ########## EXTENSION ########
  #############################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    restart: always
  
  #############################
  ######### DATABASE ##########
  #############################
  authdb:
    image: postgres
    
    
  #############################
  ######### SERVICES ##########
  #############################
  authserver:
    image: ${DOCKER_REGISTRY-}authserver
    build:
      context: .
      dockerfile: AuthServer/Dockerfile
      
      
  #############################
  ######## BACKGROUND #########
  #############################
  
  
  
volumes:
  postgres_auth_data:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local