services:
  
  #############################
  ########## EXTENSION ########
  #############################
  elasticsearch:
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=DkIedPPSCb
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    #      - ELASTICSEARCH_USERNAME=elastic
    #      - ELASTICSEARCH_PASSWORD=DkIedPPSCb
    ports:
      - 5601:5601
    volumes:
      - kibana-data:/usr/share/kibana/data
  
  #############################
  ######### DATABASE ##########
  #############################
  authdb:
    container_name: authdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=authdb
    restart: always
    ports:
      - "5001:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data1/
    
  #############################
  ######### SERVICES ##########
  #############################
  authserver:
    container_name: authserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - "DatabaseSettings:ConnectionString=Server=localhost;Port=5432;Database=authdb;User Id=admin;Password=admin1234;"
    depends_on:
      - authdb
    ports:
      - "5000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro
      
      
  #############################
  ######## BACKGROUND #########
  #############################
  